(load-file "./hex.el")
(require 'hex)
(require 'subr-x)
(ert-deftest hex--infer-base-test ()
  (let ((user-hex-clamp-ten hex-clamp-ten)
	(user-hex-clamp-hex hex-clamp-hex)
	(user-hex-max-base hex-max-base))
    (should (equal (condition-case err (hex--infer-base "37:shouldfail")
		     (error (cdr err))) `(,(format "Number exceeds maximum allowed base: %s" hex-max-base))))
    (should (equal (condition-case err (hex--infer-base "thi$willfail")
		     (error (cdr err))) '("Not a number")))
    (should (equal (condition-case err (hex--infer-base "16::f9281")
		     (error (cdr err))) '("Not a number")))
    (should (equal (condition-case err (hex--infer-base "16::f9281")
		     (error (cdr err))) '("Not a number")))
    (should (equal (condition-case err (hex--infer-base "-1:f9281")
		     (error (cdr err))) '("Not a number")))
    (should (equal (condition-case err (hex--infer-base "a1:f9281")
		     (error (cdr err))) '("Not a number")))
    (should (equal (condition-case err (hex--infer-base "1,000:f9281")
		     (error (cdr err))) '("Not a number")))
    (setq hex-clamp-ten nil)
    (setq hex-clamp-hex nil)
    (setq hex-max-base 36)
    (should (equal (hex--infer-base "efefef") 16))
    (should (equal (hex--infer-base "abcde") 15))
    (should (equal (hex--infer-base "0a0a0a") 11))
    (should (equal (hex--infer-base "75") 8))
    (should (equal (hex--infer-base "12") 3))
    (should (equal (hex--infer-base "101010") 2))
    (should (equal (hex--infer-base "ziltoid") 36))
    (should (equal (hex--infer-base "emacs") 29))
    (should (equal (hex--infer-base "0b101010") 2))
    (should (equal (hex--infer-base "0t102010") 3))
    (should (equal (hex--infer-base "0o123456") 8))
    (should (equal (hex--infer-base "0d246810") 10))
    (should (equal (hex--infer-base "0x101010") 16))
    (should (equal (hex--infer-base "22:10101")  22))
    (should (equal (hex--infer-base "1:000000") 1))
    (should (equal (hex--infer-base "7:100") 7))
    (setq hex-clamp-ten t)
    (should (equal (hex--infer-base "efefef") 16))
    (should (equal (hex--infer-base "abcde") 15))
    (should (equal (hex--infer-base "0a0a0a") 11))
    (should (equal (hex--infer-base "75") 10))
    (should (equal (hex--infer-base "12") 10))
    (should (equal (hex--infer-base "101010") 2))
    (should (equal (hex--infer-base "ziltoid") 36))
    (should (equal (hex--infer-base "emacs") 29))
    (should (equal (hex--infer-base "0b101010") 2))
    (should (equal (hex--infer-base "0t102010") 3))
    (should (equal (hex--infer-base "0o123456") 8))
    (should (equal (hex--infer-base "0d246810") 10))
    (should (equal (hex--infer-base "0x101010") 16))
    (should (equal (hex--infer-base "22:10101") 22))
    (should (equal (hex--infer-base "1:000000") 1))
    (setq hex-clamp-ten nil)
    (setq hex-clamp-hex t)
    (should (equal (hex--infer-base "efefef") 16))
    (should (equal (hex--infer-base "abcde") 16))
    (should (equal (hex--infer-base "0a0a0a") 16))
    (should (equal (hex--infer-base "75") 16))
    (should (equal (hex--infer-base "12") 16))
    (should (equal (hex--infer-base "101010") 2))
    (should (equal (hex--infer-base "ziltoid") 36))
    (should (equal (hex--infer-base "emacs") 29))
    (should (equal (hex--infer-base "0b101010") 2))
    (should (equal (hex--infer-base "0t102010") 3))
    (should (equal (hex--infer-base "0o123456") 8))
    (should (equal (hex--infer-base "0d246810") 10))
    (should (equal (hex--infer-base "0x101010") 16))
    (should (equal (hex--infer-base "22:10101") 22))
    (should (equal (hex--infer-base "1:000000") 1))
    (setq hex-clamp-ten t)
    (should (equal (hex--infer-base "efefef") 16))
    (should (equal (hex--infer-base "abcde") 16))
    (should (equal (hex--infer-base "0a0a0a") 16))
    (should (equal (hex--infer-base "75") 10))
    (should (equal (hex--infer-base "12") 10))
    (should (equal (hex--infer-base "101010") 2))
    (should (equal (hex--infer-base "ziltoid") 36))
    (should (equal (hex--infer-base "emacs") 29))
    (should (equal (hex--infer-base "0b101010") 2))
    (should (equal (hex--infer-base "0t102010") 3))
    (should (equal (hex--infer-base "0o123456") 8))
    (should (equal (hex--infer-base "0d246810") 10))
    (should (equal (hex--infer-base "0x101010") 16))
    (should (equal (hex--infer-base "22:10101") 22))
    (should (equal (hex--infer-base "1:000000") 1))
    (setq hex-clamp-ten user-hex-clamp-ten)
    (setq hex-clamp-hex user-hex-clamp-hex)
    (setq hex-max-base user-hex-max-base)))

(ert-deftest hex--strip-padding-test ()
  (let ((user-hex-padding hex-padding))
    (setq hex-padding " _.,")
    (should (equal (hex--strip-padding "1_2_3") "123"))
    (should (equal (hex--strip-padding "1...") "1"))
    (should (equal (hex--strip-padding "100,000:0,123,456,789") "100000:0123456789"))
    (should (equal (hex--strip-padding "0.,xa..b_f  f") "0xabff"))
    (should (equal (hex--strip-padding "1       7.:,30,30,30") "17:303030"))
    (setq hex-padding "0")
    (should (equal (hex--strip-padding "0b001010110100") "b11111")) ; Perhaps this should throw an exception
    (setq hex-padding user-hex-padding)))

(ert-deftest hex--digit-value-test ()
  (setq hex--digit-value-test--int "0")
  (setq hex--digit-value-test--letter "a")
  (while (and (not (equal "0" hex--digit-value-test--int))
	      (not (equal "z" hex--digit-value-test--letter)))
    (should (equal (hex--digit-value hex--digit-value-test--int)
		   (string-to-int hex--digit-value-test--int)))
    (should (equal (+ 10 (string-to-int hex--digit-value-test--int))
		   (hex--digit-value hex--digit-value-test--letter)
		   (upcase (hex--digit-value hex--digit-value-test--letter))))
    (setq hex--highest-test--int (string (1+ (aref hex--digit-value--int 0))))
    (setq hex--highest-test--letter (string (1+ (aref hex--digit-value--letter 0)))))
  (setq hex--digit-value-test--int nil)
  (setq hex--digit-value-test--letter nil))

(ert-deftest hex--reverse-string-test ()
  (should (equal (hex--reverse-string "racecar") "racecar"))
  (should (equal (hex--reverse-string "1234567890") "0987654321"))
  (should (equal (hex--reverse-string "0x10ff") "ff01x0"))
  (should (equal (hex--reverse-string "0d246810") "018642d0")))

(ert-deftest hex--strip-base-hint-test ()
  (should (equal (hex--strip-base-hint "0:0") "0"))
  (should (equal (hex--strip-base-hint "1234567890") "1234567890"))
  (should (equal (hex--strip-base-hint "0x10ff") "10ff"))
  (should (equal (hex--strip-base-hint "0d246810") "246810"))
  (should (equal (hex--strip-base-hint "0x") ""))
  (should (equal (hex--strip-base-hint "0:") ""))
  (should (equal (hex--strip-base-hint "ffffff") "ffffff"))
  (should (equal (hex--strip-base-hint "1234567890:1") "1")))

(ert-deftest hex-convert-test ()
  (should (equal (hex-convert "0xff" 10 t) "255"))
  (should (equal (hex-convert "0b1010" 10 t) "10"))
  (should (equal (hex-convert "7:100" 8 t) "61"))
  (should (equal (hex-convert "5:41300" 10 t) "2700"))
  (should (equal (hex-convert "0t10201020" 12 t) "1696")))
